repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # needed for !! tags in mkdocs.yml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  # Security checks
  - id: detect-private-key
  - id: check-case-conflict
  - id: check-symlinks

# Ruff replaces black, flake8, autoflake and isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.9.7'  # make sure this is always consistent with hatch configs
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'  # make sure this is always consistent with hatch configs
  hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive"]
      additional_dependencies: [types-tabulate, types-cachetools]

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout

# Security scanning with bandit
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.10'
  hooks:
    - id: bandit
      args: ['-c', 'pyproject.toml']
      additional_dependencies: ['bandit[toml]']

# Documentation build check
- repo: local
  hooks:
    - id: docs-build-check
      name: Check documentation builds
      entry: hatch run docs:build-check
      language: system
      pass_filenames: false
      files: '\.(md|yml|yaml|py)$'
      description: Check that documentation builds without errors
